author: 
name : "Adam Cater"
bio : "University Student in Games Programming."
links: 
- label: "Website"
icon: "fas fa-fw fa-link"
url: "https://"
- label: "Twitter"
icon: "fab fa-fw fa-twitter-square"
url: "https://twitter.com/"
- label: "Github"
icon: "fab fa-fw fa-github"
url: "https://github.com/"

footer:





